pipeline:
  input_path: "data/"
  output_path: "output/"
  target_month: "2024-01" # Month with high concentration of orders
  region_filters: ["North", "South", "East", "West"] # All available regions

data_sources:
  customers: "customers.csv"
  orders: "orders.csv"
  products: "products.csv"
  regions: "regions.csv"

quality_thresholds:
  data_quality_score: 70
  completeness_threshold: 90
  uniqueness_threshold: 95

output_formats:
  - json
  - csv
